INSERT INTO products (name, description, brand_id, category, slug, image_url, created_at, updated_at) VALUES
('Gigabyte Aero 20 OLED2', 'Gigabyte Aero 20 OLED2', 2, 'Laptop', 'gigabyte-aero-20-oled2', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại iPhone 14 Pro Max (128GB) - Chính hãng VN/A', 'Điện thoại iPhone 14 Pro Max (128GB) - Chính hãng VN/A', 2, 'Điện thoại', 'ien-thoai-iphone-14-pro-max-128gb-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Acer Chromebook Spin 713', 'Acer Chromebook Spin 713', 1, 'Laptop', 'acer-chromebook-spin-713', 'https://via.placeholder.com/500', NOW(), NOW()),
('Samsung Galaxy Book Flex 2 Alpha', 'Samsung Galaxy Book Flex 2 Alpha', 3, 'Laptop', 'samsung-galaxy-book-flex-2-alpha', 'https://via.placeholder.com/500', NOW(), NOW()),
('MacBook Air M1 13\" (8GB/256GB) - Chính hãng Apple Việt Nam', 'MacBook Air M1 13\" (8GB/256GB) - Chính hãng Apple Việt Nam', 3, 'Laptop', 'macbook-air-m1-13-8gb-256gb-chinh-hang-apple-viet-nam', 'https://via.placeholder.com/500', NOW(), NOW()),
('Dell Chromebook 3100', 'Dell Chromebook 3100', 3, 'Laptop', 'dell-chromebook-3100', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại iPhone 15 (256GB) - Chính hãng VN/A', 'Điện thoại iPhone 15 (256GB) - Chính hãng VN/A', 2, 'Điện thoại', 'ien-thoai-iphone-15-256gb-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại iPhone 14 Pro Max (256GB) - Chính hãng VN/A', 'Điện thoại iPhone 14 Pro Max (256GB) - Chính hãng VN/A', 2, 'Điện thoại', 'ien-thoai-iphone-14-pro-max-256gb-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại ASUS ROG Phone 7 (16GB/512GB) - Chính hãng', 'Điện thoại ASUS ROG Phone 7 (16GB/512GB) - Chính hãng', 3, 'Điện thoại', 'ien-thoai-asus-rog-phone-7-16gb-512gb-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại iPhone 14 Plus (128GB) - Chính hãng VN/A', 'Điện thoại iPhone 14 Plus (128GB) - Chính hãng VN/A', 1, 'Điện thoại', 'ien-thoai-iphone-14-plus-128gb-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại iPhone 15 Plus (128GB) - Chính hãng VN/A', 'Điện thoại iPhone 15 Plus (128GB) - Chính hãng VN/A', 1, 'Điện thoại', 'ien-thoai-iphone-15-plus-128gb-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại iPhone 15 (512GB) - Chính hãng VN/A', 'Điện thoại iPhone 15 (512GB) - Chính hãng VN/A', 2, 'Điện thoại', 'ien-thoai-iphone-15-512gb-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại Samsung Galaxy S23 Plus - 8GB/512GB - Chính hãng', 'Điện thoại Samsung Galaxy S23 Plus - 8GB/512GB - Chính hãng', 1, 'Điện thoại', 'ien-thoai-samsung-galaxy-s23-plus-8gb-512gb-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Điện thoại NUBIA REDMAGIC 7 PUSAR 16GB 256GB - Chính hãng', 'Điện thoại NUBIA REDMAGIC 7 PUSAR 16GB 256GB - Chính hãng', 1, 'Điện thoại', 'ien-thoai-nubia-redmagic-7-pusar-16gb-256gb-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Đồng hồ thông minh Apple Watch Series 7 GPS, 41mm – Viền nhôm dây cao su - Chính hãng VN/A', 'Đồng hồ thông minh Apple Watch Series 7 GPS, 41mm – Viền nhôm dây cao su - Chính hãng VN/A', 2, 'Đồng hồ', 'ong-ho-thong-minh-apple-watch-series-7-gps-41mm-vien-nhom-day-cao-su-chinh-hang-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Đồng hồ thông minh Apple Watch SE 2023 - GPS + LTE, 44mm - Vỏ Nhôm Dây Cao Su - VN/A', 'Đồng hồ thông minh Apple Watch SE 2023 - GPS + LTE, 44mm - Vỏ Nhôm Dây Cao Su - VN/A', 3, 'Đồng hồ', 'ong-ho-thong-minh-apple-watch-se-2023-gps-lte-44mm-vo-nhom-day-cao-su-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Đồng hồ thông minh Forerunner 255 Music - Chính Hãng', 'Đồng hồ thông minh Forerunner 255 Music - Chính Hãng', 2, 'Đồng hồ', 'ong-ho-thong-minh-forerunner-255-music-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Đồng hồ thông minh Apple Watch SE 2023 - GPS, 44mm - Vỏ Nhôm Dây Cao Su - VN/A', 'Đồng hồ thông minh Apple Watch SE 2023 - GPS, 44mm - Vỏ Nhôm Dây Cao Su - VN/A', 2, 'Đồng hồ', 'ong-ho-thong-minh-apple-watch-se-2023-gps-44mm-vo-nhom-day-cao-su-vn-a', 'https://via.placeholder.com/500', NOW(), NOW()),
('Đồng hồ thông minh Garmin Venu SQ 2 Music - Chính hãng', 'Đồng hồ thông minh Garmin Venu SQ 2 Music - Chính hãng', 2, 'Đồng hồ', 'ong-ho-thong-minh-garmin-venu-sq-2-music-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Asus ZenBook 14 OLED', 'Asus ZenBook 14 OLED', 1, 'Laptop', 'asus-zenbook-14-oled', 'https://via.placeholder.com/500', NOW(), NOW()),
('Dell XPS 13 Plus', 'Dell XPS 13 Plus', 2, 'Laptop', 'dell-xps-13-plus', 'https://via.placeholder.com/500', NOW(), NOW()),
('HP Spectre x360 14', 'HP Spectre x360 14', 3, 'Laptop', 'hp-spectre-x360-14', 'https://via.placeholder.com/500', NOW(), NOW()),
('Apple MacBook Air M2', 'Apple MacBook Air M2', 4, 'Laptop', 'apple-macbook-air-m2', 'https://via.placeholder.com/500', NOW(), NOW()),
('Lenovo ThinkPad X1 Carbon Gen 10', 'Lenovo ThinkPad X1 Carbon Gen 10', 1, 'Laptop', 'lenovo-thinkpad-x1-carbon-gen-10', 'https://via.placeholder.com/500', NOW(), NOW()),
('Microsoft Surface Laptop Studio', 'Microsoft Surface Laptop Studio', 2, 'Laptop', 'microsoft-surface-laptop-studio', 'https://via.placeholder.com/500', NOW(), NOW()),
('Samsung Galaxy Book Pro 360', 'Samsung Galaxy Book Pro 360', 3, 'Laptop', 'samsung-galaxy-book-pro-360', 'https://via.placeholder.com/500', NOW(), NOW()),
('Acer Swift X', 'Acer Swift X', 4, 'Laptop', 'acer-swift-x', 'https://via.placeholder.com/500', NOW(), NOW()),
('Razer Blade 14', 'Razer Blade 14', 1, 'Laptop', 'razer-blade-14', 'https://via.placeholder.com/500', NOW(), NOW()),
('Gigabyte Aero 15 OLED', 'Gigabyte Aero 15 OLED', 2, 'Laptop', 'gigabyte-aero-15-oled', 'https://via.placeholder.com/500', NOW(), NOW()),
('MSI Prestige 14', 'MSI Prestige 14', 3, 'Laptop', 'msi-prestige-14', 'https://via.placeholder.com/500', NOW(), NOW()),
('ASUS ROG Zephyrus G14', 'ASUS ROG Zephyrus G14', 4, 'Laptop', 'asus-rog-zephyrus-g14', 'https://via.placeholder.com/500', NOW(), NOW()),
('Acer Nitro 5', 'Acer Nitro 5', 1, 'Laptop', 'acer-nitro-5', 'https://via.placeholder.com/500', NOW(), NOW()),
('Dell G15', 'Dell G15', 2, 'Khác', 'dell-g15', 'https://via.placeholder.com/500', NOW(), NOW()),
('HP Pavilion Gaming 15', 'HP Pavilion Gaming 15', 3, 'Khác', 'hp-pavilion-gaming-15', 'https://via.placeholder.com/500', NOW(), NOW()),
('Lenovo Legion 5 Pro', 'Lenovo Legion 5 Pro', 4, 'Khác', 'lenovo-legion-5-pro', 'https://via.placeholder.com/500', NOW(), NOW()),
('Asus TUF Dash 15', 'Asus TUF Dash 15', 1, 'Laptop', 'asus-tuf-dash-15', 'https://via.placeholder.com/500', NOW(), NOW()),
('Acer Swift 3', 'Acer Swift 3', 2, 'Laptop', 'acer-swift-3', 'https://via.placeholder.com/500', NOW(), NOW()),
('Dell Inspiron 14', 'Dell Inspiron 14', 3, 'Laptop', 'dell-inspiron-14', 'https://via.placeholder.com/500', NOW(), NOW()),
('Lenovo IdeaPad 5', 'Lenovo IdeaPad 5', 1, 'Laptop', 'lenovo-ideapad-5', 'https://via.placeholder.com/500', NOW(), NOW()),
('Microsoft Surface Laptop 4', 'Microsoft Surface Laptop 4', 2, 'Laptop', 'microsoft-surface-laptop-4', 'https://via.placeholder.com/500', NOW(), NOW()),
('HP Chromebook x360 14', 'HP Chromebook x360 14', 2, 'Laptop', 'hp-chromebook-x360-14', 'https://via.placeholder.com/500', NOW(), NOW()),
('Lenovo Chromebook Duet 5', 'Lenovo Chromebook Duet 5', 3, 'Laptop', 'lenovo-chromebook-duet-5', 'https://via.placeholder.com/500', NOW(), NOW()),
('Asus Chromebook Flip CX5', 'Asus Chromebook Flip CX5', 4, 'Laptop', 'asus-chromebook-flip-cx5', 'https://via.placeholder.com/500', NOW(), NOW()),
('AAAAAAAAAAAAAAAAAAAAa', 'AAAAAAAAAAAAAAAAAAAAa', 2, 'Khác', 'aaaaaaaaaaaaaaaaaaaaa', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình Asus VA24EHF  - Chính hãng', 'Màn hình Asus VA24EHF  - Chính hãng', 2, 'Màn hình', 'man-hinh-asus-va24ehf-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình LG 24MP60G-B 23.8inch/FHD/IPS/75Hz/1ms/ Đen', 'Màn hình LG 24MP60G-B 23.8inch/FHD/IPS/75Hz/1ms/ Đen', 3, 'Màn hình', 'man-hinh-lg-24mp60g-b-23-8inch-fhd-ips-75hz-1ms-en', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình AOC G2490VX/74 23.8 inch/FHD/VA/144Hz', 'Màn hình AOC G2490VX/74 23.8 inch/FHD/VA/144Hz', 2, 'Màn hình', 'man-hinh-aoc-g2490vx-74-23-8-inch-fhd-va-144hz', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình LG 27MP60G-B 27inch/FHD/IPS/75Hz/5ms/250nitsĐen', 'Màn hình LG 27MP60G-B 27inch/FHD/IPS/75Hz/5ms/250nitsĐen', 3, 'Màn hình', 'man-hinh-lg-27mp60g-b-27inch-fhd-ips-75hz-5ms-250nitsen', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình LG 27MK600M-B 27 inch/FHD/ - Chính hãng', 'Màn hình LG 27MK600M-B 27 inch/FHD/ - Chính hãng', 2, 'Màn hình', 'man-hinh-lg-27mk600m-b-27-inch-fhd-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình LG 27GQ50F 27 inch/FHD/VA/165Hz Đen', 'Màn hình LG 27GQ50F 27 inch/FHD/VA/165Hz Đen', 2, 'Màn hình', 'man-hinh-lg-27gq50f-27-inch-fhd-va-165hz-en', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình LG 27MP60G-B 27inch/FHD/IPS/75Hz/5ms/Đen', 'Màn hình LG 27MP60G-B 27inch/FHD/IPS/75Hz/5ms/Đen', 2, 'Màn hình', 'man-hinh-lg-27mp60g-b-27inch-fhd-ips-75hz-5ms-en', 'https://via.placeholder.com/500', NOW(), NOW()),
('Tivi sony nét căng', 'Tivi sony nét căng', 3, 'Tivi', 'tivi-sony-net-cang', 'https://via.placeholder.com/500', NOW(), NOW()),
('TV Chromebook Flip CX5', 'TV Chromebook Flip CX5', 2, 'Laptop', 'tv-chromebook-flip-cx5', 'https://via.placeholder.com/500', NOW(), NOW()),
('Laptop acer 360 gaming', 'Laptop acer 360 gaming', 1, 'Laptop', 'laptop-acer-360-gaming', 'https://via.placeholder.com/500', NOW(), NOW()),
('Ipad2712 Vip pro max', 'Ipad2712 Vip pro max', 2, 'Máy tính bảng', 'ipad2712-vip-pro-max', 'https://via.placeholder.com/500', NOW(), NOW()),
('Asus gaming 1003 VN', 'Asus gaming 1003 VN', 2, 'Khác', 'asus-gaming-1003-vn', 'https://via.placeholder.com/500', NOW(), NOW()),
('Test Product Vip', 'Test Product Vip', 5, 'Khác', 'test-product-vip', 'https://via.placeholder.com/500', NOW(), NOW()),
('Màn hình 360 gaming', 'Màn hình 360 gaming', 2, 'Màn hình', 'man-hinh-360-gaming', 'https://via.placeholder.com/500', NOW(), NOW()),
('New product vip pro', 'New product vip pro', 3, 'Khác', 'new-product-vip-pro', 'https://via.placeholder.com/500', NOW(), NOW()),
('New product version 2', 'New product version 2', 2, 'Khác', 'new-product-version-2', 'https://via.placeholder.com/500', NOW(), NOW()),
('New product 11226', 'New product 11226', 1, 'Khác', 'new-product-11226', 'https://via.placeholder.com/500', NOW(), NOW()),
('Máy tính bảng iPad Pro M2 11\" 5G (128GB) - Chính hãng Apple Việt Nam', 'Máy tính bảng iPad Pro M2 11\" 5G (128GB) - Chính hãng Apple Việt Nam', 2, 'Máy tính bảng', 'may-tinh-bang-ipad-pro-m2-11-5g-128gb-chinh-hang-apple-viet-nam', 'https://via.placeholder.com/500', NOW(), NOW()),
('Máy tính bảng Samsung Galaxy Tab S9 5G 8GB/128GB - Chính hãng', 'Máy tính bảng Samsung Galaxy Tab S9 5G 8GB/128GB - Chính hãng', 1, 'Máy tính bảng', 'may-tinh-bang-samsung-galaxy-tab-s9-5g-8gb-128gb-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW()),
('Máy tính bảng Samsung Galaxy Tab S9 FE Plus Wifi 8GB/128GB', 'Máy tính bảng Samsung Galaxy Tab S9 FE Plus Wifi 8GB/128GB', 2, 'Máy tính bảng', 'may-tinh-bang-samsung-galaxy-tab-s9-fe-plus-wifi-8gb-128gb', 'https://via.placeholder.com/500', NOW(), NOW()),
('Máy tính bảng iPad Gen 9 10.2\" Wi-Fi (256GB) - Chính hãng Apple Việt Nam', 'Máy tính bảng iPad Gen 9 10.2\" Wi-Fi (256GB) - Chính hãng Apple Việt Nam', 2, 'Máy tính bảng', 'may-tinh-bang-ipad-gen-9-10-2-wi-fi-256gb-chinh-hang-apple-viet-nam', 'https://via.placeholder.com/500', NOW(), NOW()),
('Máy tính bảng OPPO Pad Air (Màu tím) - 128GB - Chính hãng', 'Máy tính bảng OPPO Pad Air (Màu tím) - 128GB - Chính hãng', 2, 'Máy tính bảng', 'may-tinh-bang-oppo-pad-air-mau-tim-128gb-chinh-hang', 'https://via.placeholder.com/500', NOW(), NOW());
